import { IStatName } from './IStatName';

export interface IStatistic {
  'timestamp': string,
  'monitors': Array<IStatName>;
  'locations': Array<IStatName>,
  'metrics': {
    'probes': number,
    'probe_ok': number,
    'probe_errors': number,
    'checks': number,
    'check_errors': number,
    'checks_maint': number,
    'maint_errors': number,
    'rtime': number,
    'ctime': number,
    'ptime': number,
    'utime': number,
    'dtime': number,
    'rtime_ok': number,
    'ctime_ok': number,
    'ptime_ok': number,
    'utime_ok': number,
    'dtime_ok': number,
    'dsize': number,
    'dev_rtime': number,
    'dev_ctime': number,
    'dev_ptime': number,
    'dev_utime': number,
    'dev_dtime': number,
    'dev_dsize': number,
    'xtime': number,
    'xtime_ok': number,
    'xspeed': number,
    'upstatus': number,
    'perfstatus': number,
    'score': number,
    'spi_score': number,
    'spi_penalty': number,
    'uptime': number,
    'downtime': number,
    'ttime': number,
    'ttime_ok': number,
    'dspeed': number,
    'slawarn': number,
    'slapoor': number,
    'apdex': number
  }
}
